# Generated by Django 4.2.17 on 2025-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='analytics',
            field=models.BooleanField(default=True),
        ),
    ]
