# Generated by Django 4.2.17 on 2025-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_table_plans_table_id_savings_table_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='savings',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='table_id',
            new_name='table',
        ),
    ]
