# Generated by Django 4.2.17 on 2025-01-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_table_id_plans_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='reality_sum',
        ),
    ]
